[2018-06-25 16:13:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost/symfony/")" at C:\Users\user\Desktop\xampp\htdocs\symfony\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost/symfony/\") at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:160)"} []
[2018-07-09 12:28:09] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-09 12:28:29] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\Users\user\Desktop\xampp\htdocs\symfony\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:161)"} []
[2018-07-09 12:28:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\Users\user\Desktop\xampp\htdocs\symfony\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:161)"} []
[2018-07-09 12:28:37] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"56ed71"},"request_uri":"http://localhost:8000/_wdt/56ed71","method":"GET"} []
[2018-07-09 12:28:44] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-09 12:28:44] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-07-09 12:28:44] request.CRITICAL: Uncaught PHP Exception RuntimeException: "There is no user provider for user "Symfony\Component\Security\Core\User\User"." at C:\Users\user\Desktop\xampp\htdocs\symfony\vendor\symfony\security\Http\Firewall\ContextListener.php line 212 {"exception":"[object] (RuntimeException(code: 0): There is no user provider for user \"Symfony\\Component\\Security\\Core\\User\\User\". at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\symfony\\security\\Http\\Firewall\\ContextListener.php:212)"} []
[2018-07-09 12:28:50] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"fea38f"},"request_uri":"http://localhost:8000/_wdt/fea38f","method":"GET"} []
[2018-07-09 12:32:42] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-09 12:32:49] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-09 12:32:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-09 12:32:55] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b9a751"},"request_uri":"http://localhost:8000/_wdt/b9a751","method":"GET"} []
[2018-07-09 12:39:59] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-07-09 12:39:59] console.ERROR: Error thrown while running command "doctrine:migrations:diff". Message: "syntax error, unexpected 'class' (T_CLASS), expecting ',' or ';'" {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'class' (T_CLASS), expecting ',' or ';' at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\src\\Entity\\User.php:11)","command":"doctrine:migrations:diff","message":"syntax error, unexpected 'class' (T_CLASS), expecting ',' or ';'"} []
[2018-07-09 12:39:59] console.DEBUG: Command "doctrine:migrations:diff" exited with code "1" {"command":"doctrine:migrations:diff","code":1} []
[2018-07-09 12:39:59] php.CRITICAL: syntax error, unexpected 'class' (T_CLASS), expecting ',' or ';' {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected 'class' (T_CLASS), expecting ',' or ';' at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\src\\Entity\\User.php:11)"} []
[2018-07-09 12:40:31] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-07-09 12:41:53] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-07-09 12:41:53] doctrine.DEBUG: CREATE TABLE migration_versions (version VARCHAR(255) NOT NULL, PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2018-07-09 12:41:54] doctrine.DEBUG: SELECT version FROM migration_versions [] []
[2018-07-09 12:41:54] doctrine.DEBUG: SELECT version FROM migration_versions WHERE version IN ('20180709104033') ORDER BY version DESC LIMIT 1 [] []
[2018-07-09 12:41:55] doctrine.DEBUG: SELECT version FROM migration_versions [] []
[2018-07-09 12:41:57] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-07-09 12:41:58] doctrine.DEBUG: CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(55) NOT NULL, password VARCHAR(55) NOT NULL, email VARCHAR(55) NOT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB [] []
[2018-07-09 12:41:58] doctrine.DEBUG: INSERT INTO migration_versions (version) VALUES (?) ["20180709104033"] []
[2018-07-09 12:41:58] doctrine.DEBUG: "COMMIT" [] []
[2018-07-09 13:04:16] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-07-09 13:04:17] doctrine.DEBUG: DELETE FROM user [] []
[2018-07-09 13:04:19] doctrine.DEBUG: INSERT INTO user (username, password, email) VALUES (?, ?, ?) {"1":"admin","2":"$2y$13$5zzFfjko26bqATtk2v6 [...]","3":null} []
[2018-07-09 13:04:20] doctrine.DEBUG: "ROLLBACK" [] []
[2018-07-09 13:04:20] console.ERROR: Error thrown while running command "doctrine:fixtures:load". Message: "An exception occurred while executing 'INSERT INTO user (username, password, email) VALUES (?, ?, ?)' with params ["admin", "$2y$13$5zzFfjko26bqATtk2v6ET.WzqYqq5siRY.BHNx\/XEENJuqLrQxFyC", null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null" {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, password, email) VALUES (?, ?, ?)' with params [\"admin\", \"$2y$13$5zzFfjko26bqATtk2v6ET.WzqYqq5siRY.BHNx\\/XEENJuqLrQxFyC\", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:122, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:143, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:141)","command":"doctrine:fixtures:load","message":"An exception occurred while executing 'INSERT INTO user (username, password, email) VALUES (?, ?, ?)' with params [\"admin\", \"$2y$13$5zzFfjko26bqATtk2v6ET.WzqYqq5siRY.BHNx\\/XEENJuqLrQxFyC\", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null"} []
[2018-07-09 13:04:20] console.DEBUG: Command "doctrine:fixtures:load" exited with code "1" {"command":"doctrine:fixtures:load","code":1} []
[2018-07-09 13:05:15] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-07-09 13:05:16] doctrine.DEBUG: DELETE FROM user [] []
[2018-07-09 13:05:18] doctrine.DEBUG: INSERT INTO user (username, password, email) VALUES (?, ?, ?) {"1":"admin","2":"$2y$13$Ab/TD7lr.tccFOV4lNZ [...]","3":"no-reply@overseas.media"} []
[2018-07-09 13:05:18] doctrine.DEBUG: "COMMIT" [] []
[2018-07-09 13:05:53] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-09 13:06:14] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-09 13:06:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-09 13:06:18] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-09 13:06:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-09 13:06:22] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e83e65"},"request_uri":"http://localhost:8000/_wdt/e83e65","method":"GET"} []
[2018-07-09 13:06:35] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"POST"} []
[2018-07-09 13:06:36] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.email AS email_4 FROM user t0 WHERE t0.username = ? LIMIT 1 ["admin"] []
[2018-07-09 13:06:38] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\symfony\\security\\Core\\Authentication\\Provider\\UserAuthenticationProvider.php:84, Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): The presented password is invalid. at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\symfony\\security\\Core\\Authentication\\Provider\\DaoAuthenticationProvider.php:58)"} []
[2018-07-09 13:06:38] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2018-07-09 13:06:40] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-09 13:06:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-09 13:06:45] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"02e80d"},"request_uri":"http://localhost:8000/_wdt/02e80d","method":"GET"} []
[2018-07-09 13:19:26] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (No connection could be made because the target machine actively refused it. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-09 13:19:30] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-09 13:19:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-09 13:19:34] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"750881"},"request_uri":"http://localhost:8000/_wdt/750881","method":"GET"} []
[2018-07-09 13:19:43] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"POST"} []
[2018-07-09 13:19:44] security.INFO: User has been authenticated successfully. {"username":"admin"} []
[2018-07-09 13:19:44] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-07-09 13:19:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8000/login")" at C:\Users\user\Desktop\xampp\htdocs\symfony\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8000/login\") at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:161)"} []
[2018-07-09 13:19:49] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"bc84b1"},"request_uri":"http://localhost:8000/_wdt/bc84b1","method":"GET"} []
[2018-07-09 13:20:04] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-09 13:20:04] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-07-09 13:20:04] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider","username":"admin"} []
[2018-07-09 13:20:05] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-07-09 13:20:06] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2b7109"},"request_uri":"http://localhost:8000/_wdt/2b7109","method":"GET"} []
[2018-07-09 17:42:04] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-09 17:42:16] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-09 17:42:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-09 17:42:23] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9a56b1"},"request_uri":"http://localhost:8000/_wdt/9a56b1","method":"GET"} []
[2018-07-10 07:03:02] doctrine.DEBUG: CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(55) NOT NULL, password VARCHAR(55) NOT NULL, email VARCHAR(55) NOT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB [] []
[2018-07-10 07:03:19] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-07-10 07:03:19] doctrine.DEBUG: DELETE FROM user [] []
[2018-07-10 07:03:19] doctrine.DEBUG: "ROLLBACK" [] []
[2018-07-10 07:03:20] console.ERROR: Error thrown while running command "doctrine:fixtures:load". Message: "No encoder has been configured for account "App\Entity\User"." {"exception":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"App\\Entity\\User\". at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\security\\Core\\Encoder\\EncoderFactory.php:51)","command":"doctrine:fixtures:load","message":"No encoder has been configured for account \"App\\Entity\\User\"."} []
[2018-07-10 07:03:20] console.DEBUG: Command "doctrine:fixtures:load" exited with code "1" {"command":"doctrine:fixtures:load","code":1} []
[2018-07-10 07:06:38] console.ERROR: Error thrown while running command ""make:cotroller"". Message: "Command "make:cotroller" is not defined.  Did you mean one of these?     make:auth     make:command     make:controller     make:crud     make:entity     make:fixtures     make:form     make:functional-test     make:migration     make:serializer:encoder     make:subscriber     make:twig-extension     make:unit-test     make:validator     make:voter" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"make:cotroller\" is not defined.\n\nDid you mean one of these?\n    make:auth\n    make:command\n    make:controller\n    make:crud\n    make:entity\n    make:fixtures\n    make:form\n    make:functional-test\n    make:migration\n    make:serializer:encoder\n    make:subscriber\n    make:twig-extension\n    make:unit-test\n    make:validator\n    make:voter at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\console\\Application.php:632)","command":"\"make:cotroller\"","message":"Command \"make:cotroller\" is not defined.\n\nDid you mean one of these?\n    make:auth\n    make:command\n    make:controller\n    make:crud\n    make:entity\n    make:fixtures\n    make:form\n    make:functional-test\n    make:migration\n    make:serializer:encoder\n    make:subscriber\n    make:twig-extension\n    make:unit-test\n    make:validator\n    make:voter"} []
[2018-07-10 07:15:25] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-10 07:15:33] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-10 07:15:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-10 07:15:37] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"77be2e"},"request_uri":"http://localhost:8000/_wdt/77be2e","method":"GET"} []
[2018-07-10 07:15:53] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-10 07:16:04] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"POST"} []
[2018-07-10 07:16:04] security.INFO: User has been authenticated successfully. {"username":"admin"} []
[2018-07-10 07:16:04] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-07-10 07:16:07] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8000/login")" at C:\Users\user\Desktop\xampp\htdocs\symfony_login\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8000/login\") at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:162)"} []
[2018-07-10 07:16:10] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"7b1708"},"request_uri":"http://localhost:8000/_wdt/7b1708","method":"GET"} []
[2018-07-10 07:16:17] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-10 07:16:18] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-07-10 07:16:18] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider","username":"admin"} []
[2018-07-10 07:16:19] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-07-10 07:16:20] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e8c8d8"},"request_uri":"http://localhost:8000/_wdt/e8c8d8","method":"GET"} []
[2018-07-10 07:17:09] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-07-10 07:17:09] doctrine.DEBUG: DELETE FROM user [] []
[2018-07-10 07:17:09] doctrine.DEBUG: "ROLLBACK" [] []
[2018-07-10 07:17:09] console.ERROR: Error thrown while running command "doctrine:fixtures:load". Message: "No encoder has been configured for account "App\Entity\User"." {"exception":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"App\\Entity\\User\". at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\security\\Core\\Encoder\\EncoderFactory.php:51)","command":"doctrine:fixtures:load","message":"No encoder has been configured for account \"App\\Entity\\User\"."} []
[2018-07-10 07:17:09] console.DEBUG: Command "doctrine:fixtures:load" exited with code "1" {"command":"doctrine:fixtures:load","code":1} []
[2018-07-10 14:21:17] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-07-10 14:21:19] doctrine.DEBUG: DELETE FROM user [] []
[2018-07-10 14:21:19] doctrine.DEBUG: "ROLLBACK" [] []
[2018-07-10 14:21:19] console.ERROR: Error thrown while running command "doctrine:fixtures:load". Message: "No encoder has been configured for account "App\Entity\User"." {"exception":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"App\\Entity\\User\". at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\security\\Core\\Encoder\\EncoderFactory.php:51)","command":"doctrine:fixtures:load","message":"No encoder has been configured for account \"App\\Entity\\User\"."} []
[2018-07-10 14:21:19] console.DEBUG: Command "doctrine:fixtures:load" exited with code "1" {"command":"doctrine:fixtures:load","code":1} []
[2018-07-15 06:03:24] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (No connection could be made because the target machine actively refused it. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-15 06:03:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\Users\user\Desktop\xampp\htdocs\symfony_login\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:162)"} []
[2018-07-15 06:03:38] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"275e77"},"request_uri":"http://localhost:8000/_wdt/275e77","method":"GET"} []
[2018-07-15 06:03:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8000/")" at C:\Users\user\Desktop\xampp\htdocs\symfony_login\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/\") at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:50)"} []
[2018-07-15 06:03:50] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-15 06:03:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-15 06:03:54] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"442b7c"},"request_uri":"http://localhost:8000/_wdt/442b7c","method":"GET"} []
[2018-07-15 06:04:24] doctrine.DEBUG: CREATE TABLE user (id INTEGER NOT NULL, username VARCHAR(55) NOT NULL, password VARCHAR(55) NOT NULL, email VARCHAR(55) NOT NULL, PRIMARY KEY(id)) [] []
[2018-07-15 06:04:24] doctrine.DEBUG: CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON user (username) [] []
[2018-07-15 06:04:24] doctrine.DEBUG: CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email) [] []
[2018-07-15 06:04:47] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-07-15 06:04:48] doctrine.DEBUG: DELETE FROM user [] []
[2018-07-15 06:04:51] doctrine.DEBUG: INSERT INTO user (username, password, email) VALUES (?, ?, ?) {"1":"admin","2":"$2y$13$ZBqal/hdUv7upJF4luR [...]","3":"no-reply@overseas.media"} []
[2018-07-15 06:04:51] doctrine.DEBUG: "COMMIT" [] []
[2018-07-15 06:05:34] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-15 06:05:38] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-15 06:05:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-15 06:05:41] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"230b93"},"request_uri":"http://localhost:8000/_wdt/230b93","method":"GET"} []
[2018-07-15 06:05:48] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"POST"} []
[2018-07-15 06:05:49] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.email AS email_4 FROM user t0 WHERE t0.username = ? LIMIT 1 ["admin"] []
[2018-07-15 06:05:51] security.INFO: User has been authenticated successfully. {"username":"admin"} []
[2018-07-15 06:05:52] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-07-15 06:05:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8000/login")" at C:\Users\user\Desktop\xampp\htdocs\symfony_login\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8000/login\") at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:162)"} []
[2018-07-15 06:05:56] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0a08d9"},"request_uri":"http://localhost:8000/_wdt/0a08d9","method":"GET"} []
[2018-07-15 06:06:02] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-15 06:06:02] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-07-15 06:06:03] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.email AS email_4 FROM user t0 WHERE t0.id = ? [1] []
[2018-07-15 06:06:03] security.DEBUG: Token was deauthenticated after trying to refresh it. {"username":"admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-07-15 06:06:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-15 06:06:05] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f379ae"},"request_uri":"http://localhost:8000/_wdt/f379ae","method":"GET"} []
[2018-07-15 06:06:19] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-15 06:06:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-15 06:06:22] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1192d8"},"request_uri":"http://localhost:8000/_wdt/1192d8","method":"GET"} []
[2018-07-15 06:08:24] doctrine.DEBUG: SELECT * FROM user [] []
[2018-07-15 06:19:26] doctrine.DEBUG: CREATE TABLE user (id INTEGER NOT NULL, username VARCHAR(55) NOT NULL, password VARCHAR(55) NOT NULL, email VARCHAR(55) NOT NULL, PRIMARY KEY(id)) [] []
[2018-07-15 06:19:26] doctrine.DEBUG: CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON user (username) [] []
[2018-07-15 06:19:26] doctrine.DEBUG: CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email) [] []
[2018-07-15 06:19:39] doctrine.DEBUG: "START TRANSACTION" [] []
[2018-07-15 06:19:39] doctrine.DEBUG: DELETE FROM user [] []
[2018-07-15 06:19:41] doctrine.DEBUG: INSERT INTO user (username, password, email) VALUES (?, ?, ?) {"1":"admin","2":"$2y$13$04HOJ/WCqjEla3WXFFK [...]","3":"no-reply@overseas.media"} []
[2018-07-15 06:19:42] doctrine.DEBUG: "COMMIT" [] []
[2018-07-15 06:19:55] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (No connection could be made because the target machine actively refused it. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-15 06:20:01] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-15 06:20:01] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-07-15 06:20:02] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.email AS email_4 FROM user t0 WHERE t0.id = ? [1] []
[2018-07-15 06:20:03] security.DEBUG: Token was deauthenticated after trying to refresh it. {"username":"admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-07-15 06:20:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-15 06:20:06] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"025a9e"},"request_uri":"http://localhost:8000/_wdt/025a9e","method":"GET"} []
[2018-07-15 06:20:16] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"POST"} []
[2018-07-15 06:20:17] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.email AS email_4 FROM user t0 WHERE t0.username = ? LIMIT 1 ["admin"] []
[2018-07-15 06:20:19] security.INFO: User has been authenticated successfully. {"username":"admin"} []
[2018-07-15 06:20:19] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-07-15 06:20:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8000/login")" at C:\Users\user\Desktop\xampp\htdocs\symfony_login\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8000/login\") at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:161)"} []
[2018-07-15 06:20:24] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"546ba9"},"request_uri":"http://localhost:8000/_wdt/546ba9","method":"GET"} []
[2018-07-15 06:20:31] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-15 06:20:31] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-07-15 06:20:31] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.email AS email_4 FROM user t0 WHERE t0.id = ? [1] []
[2018-07-15 06:20:31] security.DEBUG: Token was deauthenticated after trying to refresh it. {"username":"admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-07-15 06:20:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-15 06:20:33] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"aa8cc5"},"request_uri":"http://localhost:8000/_wdt/aa8cc5","method":"GET"} []
[2018-07-15 06:31:45] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\user\\\\Desktop\\\\xampp\\\\htdocs\\\\symfony_login\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-07-15 06:31:55] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-15 06:31:55] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-07-15 06:31:56] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.email AS email_4 FROM user t0 WHERE t0.id = ? [1] []
[2018-07-15 06:31:56] security.DEBUG: Token was deauthenticated after trying to refresh it. {"username":"admin","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2018-07-15 06:31:56] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-07-15 06:32:02] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f542ac"},"request_uri":"http://localhost:8000/_wdt/f542ac","method":"GET"} []
[2018-07-15 06:32:10] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"POST"} []
[2018-07-15 06:32:11] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.email AS email_4 FROM user t0 WHERE t0.username = ? LIMIT 1 ["admin"] []
[2018-07-15 06:32:13] security.INFO: User has been authenticated successfully. {"username":"admin"} []
[2018-07-15 06:32:13] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-07-15 06:32:15] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8000/login")" at C:\Users\user\Desktop\xampp\htdocs\symfony_login\vendor\symfony\http-kernel\EventListener\RouterListener.php line 139 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8000/login\") at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:139, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\user\\Desktop\\xampp\\htdocs\\symfony_login\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:161)"} []
[2018-07-15 06:32:18] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"43ce3d"},"request_uri":"http://localhost:8000/_wdt/43ce3d","method":"GET"} []
[2018-07-15 06:32:22] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2018-07-15 06:32:23] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-07-15 06:32:23] doctrine.DEBUG: SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.email AS email_4 FROM user t0 WHERE t0.id = ? [1] []
[2018-07-15 06:32:23] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"admin"} []
[2018-07-15 06:32:24] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-07-15 06:32:25] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ab0fd6"},"request_uri":"http://localhost:8000/_wdt/ab0fd6","method":"GET"} []
